site_name: CommBank Engineering
site_url: https://docs.commbank.dev
nav:
  - Home: index.md
  - About: about.md
repo_url: https://github.com/CBA-Utilities/commbank-dev.docs
theme:
  name: cinder
  custom_dir: docs-theme-ext
  logo: docs-theme-ext/logo.png
  user_color_mode_toggle: true
  disable_nav_previous_next: true
  disable_footer_except_revision: true